language: php

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - nightly

env:
  - DB=mysql
  - DB=sqlite
  - DB=pgsql

before_install:
  - if [[ $DB == 'mysql' && $MYSQL_VERSION == '5.7' ]]; then ./test/travis/install-mysql-5.7.sh; fi
  - if [[ $DB == 'mysql' ]]; then mysql -u root -e 'select version()'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -U postgres -c 'SHOW SERVER_VERSION'; fi
  - composer self-update
  - composer update $COMPOSER_FLAGS --prefer-dist
  - cp test/app/config/parameters.yml.dist test/app/config/parameters.yml
  - php test/app/console doctrine:database:create
  - php test/app/console doctrine:schema:drop --force
  - php test/app/console doctrine:schema:create

script: ./bin/phpunit -c test/travis/$DB.travis.xml

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: NAME="MySQL 5.6" DB=mysql
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - mysql-server-5.6
          - mysql-client-core-5.6
          - mysql-client-5.6
    - php: 7.1
      env: NAME="MySQL 5.7" DB=mysql MYSQL_VERSION=5.7
      sudo: required
    - php: 7.1
      env: NAME="PostgreSQL 9.2" DB=pgsql
      addons:
        postgresql: 9.2
    - php: 7.1
      env: NAME="PostgreSQL 9.3" DB=pgsql
      addons:
        postgresql: 9.3
    - php: 7.1
      env: NAME="PostgreSQL 9.4" DB=pgsql
      addons:
        postgresql: 9.4
  allow_failures:
    - php: nightly

notifications:
    email: false