jms_serializer:
    metadata:
        directories:
            dreamcommerce-objectaudit-revision:
                namespace_prefix: "DreamCommerce\\Component\\ObjectAudit\\Revision"
                path: "@DreamCommerceObjectAuditBundle/Resources/config/serializer"