jms_serializer:
    metadata:
        directories:
            dreamcommerce-objectaudit:
                namespace_prefix: "DreamCommerce\\Component\\ObjectAudit"
                path: "@DreamCommerceObjectAuditBundle/Resources/config/serializer"